name: Create Azure Resource Group

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  create-rg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name my-resource-group \
            --location eastus
